const express = require("express");
const organisationController = require("../controllers/organisationController");
const router = express.Router();
router.get("/:id", organisationController.findById);
router.post("/register", organisationController.create);
router.post("/login", organisationController.login);
router.post("/:id/createuser", organisationController.createUser);
router.get("/", organisationController.getAll);
router.put("/:id", organisationController.update);
module.exports = router;
